src/Entity/Auteur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\AuteurRepository;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=1)
     * @Assert\Choice({"M", "F"})
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     * @Assert\Type("DateTime")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255)
    * @Assert\Country
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, inversedBy="auteurs")
     */
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function __toString()
    {
        return $this->nom_prenom;
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\LivreRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LivreRepository::class)
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=13)
    * @Assert\Regex("/97[89][- ]?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9]$/")
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     */
    private $nombre_pages;

    /**
     * @ORM\Column(type="date")
     * @Assert\Type("DateTime")
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="integer")
     * * @Assert\Range(
     *      min = 0,
     *      max = 20,
    *      notInRangeMessage = "Must be between {{ min }} and {{ max }}")
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, mappedBy="livres")
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres")
     */
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNombrePages(): ?int
    {
        return $this->nombre_pages;
    }

    public function setNombrePages(int $nombre_pages): self
    {
        $this->nombre_pages = $nombre_pages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
            $auteur->addLivre($this);
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        if ($this->auteurs->removeElement($auteur)) {
            $auteur->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }
    public function __toString()
    {
        return $this->titre;
    }
}

src/Form/AuteurType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class AuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_prenom', null, [
                'label' => 'Nom et Prenom',
                'attr' => ['class' => 'form-control my-2']
            ])
            ->add('sexe', ChoiceType::class, [
                'choices'  => [
                    'Féminin' => 'f',
                    'Masculin' => 'm',
                ],
                'attr' => ['class' => 'form-control my-2']
            ])
            ->add('date_de_naissance', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control my-2'],
            ])
            ->add('nationalite', null, ['attr' => ['class' => 'form-control my-2']]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Auteur::class,
        ]);
    }
}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use App\Entity\Auteur;
use App\Form\AuteurType;
use App\Repository\AuteurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/auteur")
 */
class AuteurController extends AbstractController
{
    /**
     * @Route("/", name="auteur_index", methods={"GET"})
     */
    public function index(AuteurRepository $auteurRepository): Response
    {
        $auteurs = $auteurRepository->findAll();

        return $this->render('auteur/index.html.twig', [
            'auteurs' => $auteurs,
        ]);
    }

    /**
     * @Route("/new", name="auteur_new", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $auteur = new Auteur();
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($auteur);
            $entityManager->flush();
            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/new.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="auteur_show", methods={"GET"})
     */
    public function show(Auteur $auteur): Response
    {
        // dd($auteur->getLivres());
        return $this->render('auteur/show.html.twig', [
            'auteur' => $auteur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="auteur_edit", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/edit.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="auteur_delete", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $auteur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($auteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/auteur/_delete_form.html.twig
<form method="post" action="{{ path('auteur_delete', {'id': auteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ auteur.id) }}">
    <button class="btn btn-danger mt-1 mb-1">Delete</button>
     <a href="{{ path('auteur_show', {'id': auteur.id}) }}" class="btn btn-success mt-1 mb-1">show</a>
                    <a href="{{ path('auteur_edit', {'id': auteur.id}) }}" class="btn btn-info mt-1 mb-1">edit</a>
</form>

templates/auteur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mt-1 mb-1">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/auteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Auteur{% endblock %}

{% block body %}
    <h1>Edit Auteur</h1>

    {{ include('auteur/_form.html.twig', {'button_label': 'Update'}) }}


    
{% endblock %}

templates/auteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur index{% endblock %}

{% block body %}
        <a href="{{ path('auteur_new') }}" class="btn btn-success mt-3" >Ajouter nouvelle aute</a><br><br>
<div class="card-columns">
  {% for auteur in auteurs %}
  <div class="card">
    <img class="card-img-top" src="{{ asset('pic/book.jpg') }}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">{{ auteur.nomPrenom }}</h5>
      <p class="card-text">
      <h6>Sexe  : {{ auteur.sexe }}</h6>
        <h6>nationalite :  {{ auteur.nationalite }}</h6>
      </p>
      <p class="card-text"><small class="text-muted">{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d') : '' }}</small>
      
                     {{ include('auteur/_delete_form.html.twig') }}
      </p>
    </div>
  </div>
   

        {% else %}
           
                <h1 >no records found</h1>
           
        {% endfor %}
        </div>

    
{% endblock %}

templates/auteur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Auteur{% endblock %}

{% block body %}
    <h1>Create new Auteur</h1>

    {{ include('auteur/_form.html.twig') }}

    
{% endblock %}

templates/auteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur{% endblock %}

{% block body %}
    <h1>Auteur</h1>

         <div class="card bg-dark text-black" width="100%" height="100%">
  <img class="card-img" src="{{ asset('pic/book1.jpg') }}" alt="Card image">
  <div class="card-img-overlay">
 <a href="{{ path('auteur_edit', {'id': auteur.id}) }}" class="btn btn-success mt-1 mb-1">edit</a>
    <h2 class="card-title">{{ auteur.nomPrenom }}</h2>
    <p class="card-text">
        <h4>Sexe  : {{ auteur.sexe }}</h4>
        <h4>Date de naissance:  {{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d') : '' }}</h4>
        <h4>Nationalite : {{ auteur.nationalite }}</h4><br>
    </p>
    <p class="card-text">
    <br>
    <h3>Livres </h3>
        <div class="card-columns">
  {% for livre in livres %}
  <div class="card">
   
    <div class="card-body">
      <h5 class="card-title">{{ livre.titre }}</h5>
      <p class="card-text">
      <h6>ISBN  : {{ livre.isbn }}</h6>
        <h6>Nombre des pages :  {{ livre.nombrePages }}</h6>
        <h6>Note : {{ livre.note  }}</h6>
      </p>
      <p class="card-text"><small class="text-muted">{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</small>
      
                    
      </p>
    </div>
  </div>
   
  
    {% endfor %}
</div>
  
      </p>
    </div>
   
           
      
    


   
{% endblock %}